name = the_space_mod
title = The Space Mod
description = The space mod is an in development mod that will feature space travel, to a space station and the moon, oxigen managment, and machines
depends = default, 3d_armor
