name = space_suits
description = space suits module of the space mod 
title = Space Suits
depends = default, space_core, 3d_armor, 3d_armor_ip, 3d_armor_sfinv, 3d_armor_stand, 3d_armor_ui, armor_admin